export const exerciseData = [
  {
    id: "turkish-qwerty",
    type: "Türkçe QWERTY Klavye",
    data: [
      {
        id: "turkish-qwerty-ex-1",
        name: "Sol Orta Sıra",
        description: "Sol orta karakterler (a, s, d, f, boşluk )",
        characters: ["a", "s", "d", "f"],
        difficulty: "easy",
      },
      {
        id: "turkish-qwerty-ex-2",
        name: "Sağ Orta Sıra",
        description: "Sağ orta karakterler (j, k, l, ş, i, boşluk)",
        characters: ["j", "k", "l", "ş", "i"],
        difficulty: "easy",
      },
      {
        id: "turkish-qwerty-ex-3",
        name: "Sol Üst Sıra",
        description: "Sol üst karakterler (q, w, e, r, t boşluk )",
        characters: ["q", "w", "e", "r", "t"],
        difficulty: "easy",
      },
      {
        id: "turkish-qwerty-ex-4",
        name: "Sağ Üst Sıra",
        description: "Sağ üst karakterler (u, ı, o ,p, ğ, ü boşluk)",
        characters: ["u", "ı", "o", "p", "ğ", "ü"],
        difficulty: "easy",
      },
      {
        id: "turkish-qwerty-ex-5",
        name: "Sol Alt Sıra",
        description: "Sol üst karakterler (z, x, c, v, b, y boşluk )",
        characters: ["q", "w", "e", "r", "t", "y"],
        difficulty: "easy",
      },
      {
        id: "turkish-qwerty-ex-6",
        name: "Sağ Alt Sıra",
        description: "Sağ üst karakterler (n, m, ö ,ç, . boşluk)",
        characters: ["n", "m", "ö", "ç", "."],
        difficulty: "easy",
      },
      {
        id: "turkish-qwerty-ex-7",
        name: "Sol Orta Sıra",
        description: "Sol orta karakterler (a, s, d, f, boşluk )",
        characters: ["a", "s", "d", "f"],
        difficulty: "normal",
      },
      {
        id: "turkish-qwerty-ex-8",
        name: "Sağ Orta Sıra",
        description: "Sağ orta karakterler (j, k, l, ş, i, boşluk)",
        characters: ["j", "k", "l", "ş", "i"],
        difficulty: "normal",
      },
      {
        id: "turkish-qwerty-ex-9",
        name: "Sağ Orta Sıra",
        description: "Sağ orta karakterler (j, k, l, ş, i, boşluk)",
        characters: [
          "q",
          "w",
          "e",
          "r",
          "t",
          "a",
          "s",
          "d",
          "f",
          "g",
          "h",
          "z",
          "x",
          "c",
          "v",
          "b",
        ],
        difficulty: "hard",
      },
    ],
  },
  {
    id: "turkish-F",
    type: "Türkçe F Klavye",
    data: [],
  },
];
